CREATE TABLE MEMBER (
	MEM_NO	    NUMBER	    	PRIMARY KEY,
	MAIL    	VARCHAR2(4000)  NOT NULL,
	PASSWORD	VARCHAR2(4000),
	MEM_ID	    VARCHAR2(4000)  NOT NULL,
	LANGUAGE	VARCHAR2(4000),
	STATUS  	NUMBER	        DEFAULT 0,
	NAME	    VARCHAR2(4000),
	BIRTH	    DATE,
	GENDER  	VARCHAR2(4000),
	PHONE	    VARCHAR2(4000),
	NICK	    VARCHAR2(4000),
	IMAGE	    VARCHAR2(4000),
	ITRO	    VARCHAR2(4000),
	HEIGHT  	NUMBER,
	SKILL	    NUMBER,
	DAYS	    NUMBER	        DEFAULT 1,
	CARDIO  	NUMBER	        DEFAULT 0
);

CREATE TABLE FOLLOW (
	MEM_NO      NUMBER  REFERENCES MEMBER(MEM_NO),
	FOLLOWING	NUMBER  REFERENCES MEMBER(MEM_NO)
);

CREATE TABLE BLOCK (
	MEM_NO  	NUMBER  REFERENCES MEMBER(MEM_NO),
	BLOCKING	NUMBER	REFERENCES MEMBER(MEM_NO)
);

CREATE TABLE MEM_DATE (
	MEM_NO	NUMBER		    REFERENCES MEMBER(MEM_NO),
	DAILY	DATE		    NOT NULL,
	WEIGHT	NUMBER,
	CAL	    NUMBER,
	EXS 	VARCHAR2(4000),
	MEMO	VARCHAR2(4000)
);

CREATE TABLE MUSCLE (
	MUSC_ID	VARCHAR2(4000)		PRIMARY KEY,
	NAME_KO	VARCHAR2(4000),
	NAME_JP	VARCHAR2(4000),
	NAME_EN	VARCHAR2(4000)
);

CREATE TABLE EQUIPMENT (
	EQUIP_ID	VARCHAR2(4000)	PRIMARY KEY,
	NAME_KO	    VARCHAR2(4000),
	NAME_JP	    VARCHAR2(4000),
	NAME_EN	    VARCHAR2(4000)
);

CREATE TABLE EQUIP_LIST (
	MEM_NO 	    NUMBER		    REFERENCES MEMBER(MEM_NO),
	EQUIP_ID	VARCHAR2(4000)	REFERENCES EQUIPMENT(EQUIP_ID)
);

CREATE TABLE EXERCISE (
	EX_NO	    NUMBER		    PRIMARY KEY,
	MUSC_ID	    VARCHAR2(4000)	REFERENCES MUSCLE(MUSC_ID),
	EQUIP_ID	VARCHAR2(4000)  REFERENCES EQUIPMENT(EQUIP_ID),
	DIFF	    NUMBER	    	NOT NULL,
	FREQ	    NUMBER	    	NOT NULL,
	IMAGE	    VARCHAR2(4000),
	NAME_KO	    VARCHAR2(4000),
	EFFECT_KO	VARCHAR2(4000),
	GUIDE_KO	VARCHAR2(4000),
	NAME_JP	    VARCHAR2(4000),
	EFFECT_JP	VARCHAR2(4000),
	GUIDE_JP	VARCHAR2(4000),
	NAME_EN	    VARCHAR2(4000),
	EFFECT_EN	VARCHAR2(4000),
	GUIDE_EN	VARCHAR2(4000)
);

CREATE TABLE EX_BOOK (
	MEM_NO	NUMBER	REFERENCES MEMBER(MEM_NO),
	EX_NO	NUMBER	REFERENCES EXERCISE(EX_NO)
);

CREATE TABLE ROUT_DEFAULT (
	ROUT_D_NO	NUMBER	    	PRIMARY KEY,
	STEP	    VARCHAR2(4000),
	NAME_KO	    VARCHAR2(4000),
	GUIDE_KO	VARCHAR2(4000),
	NAME_JP	    VARCHAR2(4000),
	GUIDE_JP	VARCHAR2(4000),
	NAME_EN	    VARCHAR2(4000),
	GUIDE_EN	VARCHAR2(4000)
);

CREATE TABLE ROUT_D_BOOK (
	MEM_NO	    NUMBER		REFERENCES MEMBER(MEM_NO),
	ROUT_D_NO	NUMBER		REFERENCES ROUT_DEFAULT(ROUT_D_NO)
);

CREATE TABLE ROUT_GENERATED (
	ROUT_G_NO	NUMBER		    PRIMARY KEY,
	MEM_NO 	NUMBER		    REFERENCES MEMBER(MEM_NO),
	STEP	    VARCHAR2(4000),
	TIME	    DATE
);

CREATE TABLE FEED (
	FEED_NO	NUMBER	    	PRIMARY KEY,
	MEM_NO	NUMBER	    	REFERENCES MEMBER(MEM_NO),
	IMAGE	VARCHAR2(4000),
	CONTENT	VARCHAR2(4000),
	TIME	DATE	        DEFAULT SYSDATE,
	HIDE	NUMBER      	DEFAULT 0
);

CREATE TABLE FEED_LIKE (
	MEM_NO	NUMBER	REFERENCES MEMBER(MEM_NO),
	FEED_NO	NUMBER	REFERENCES FEED(FEED_NO)
);

CREATE TABLE FEED_BOOK (
	MEM_NO	NUMBER	REFERENCES MEMBER(MEM_NO),
	FEED_NO	NUMBER	REFERENCES FEED(FEED_NO)
);

CREATE TABLE COMMENTS (
	COM_NO	    NUMBER		    PRIMARY KEY,
	MEM_NO  	NUMBER	    	REFERENCES MEMBER(MEM_NO),
	FEED_NO 	NUMBER	    	REFERENCES FEED(FEED_NO),
	COM_P_NO	NUMBER,
	CONTENT 	VARCHAR2(4000),
	TIME	    DATE        	DEFAULT SYSDATE,
	DELETED 	NUMBER      	DEFAULT 0
);

CREATE TABLE COM_LIKE (
	MEM_NO	NUMBER	REFERENCES MEMBER(MEM_NO),
	COM_NO	NUMBER	REFERENCES COMMENTS(COM_NO)
);

CREATE TABLE NOTIFY (
	NOTI_NO	NUMBER	    	PRIMARY KEY,
	MEM_NO	NUMBER	    	REFERENCES MEMBER(MEM_NO),
	TYPE	VARCHAR2(4000),
	CONTENT	VARCHAR2(4000),
	TIME	DATE            DEFAULT SYSDATE,
	VERIFIED                NUMBER
);

CREATE TABLE MENU (
	MENU_ID	VARCHAR2(4000)	PRIMARY KEY,
	NAME_KO	VARCHAR2(4000),
	NAME_JP	VARCHAR2(4000),
	NAME_EN	VARCHAR2(4000)
);

CREATE SEQUENCE SEQ_MEMBER;
CREATE SEQUENCE SEQ_EXERCISE;
CREATE SEQUENCE SEQ_ROUT_D;
CREATE SEQUENCE SEQ_ROUT_T;
CREATE SEQUENCE SEQ_ROUT_G;
CREATE SEQUENCE SEQ_FEED;
CREATE SEQUENCE SEQ_COMMENT;
CREATE SEQUENCE SEQ_NOTIFY;

ALTER TABLE MEMBER RENAME COLUMN ITRO TO INTRO;
ALTER TABLE MEMBER DROP COLUMN NICK;

DROP TABLE MENU;
DROP TABLE ROUT_GENERATED;
CREATE TABLE ROUT_GENERATED (
    ROUT_G_NO    NUMBER            PRIMARY KEY,
    MEM_NO         NUMBER            REFERENCES MEMBER(MEM_NO),
    NAME        VARCHAR2(4000),
    STEP        VARCHAR2(4000),
    EQUIP        VARCHAR2(4000),
    SKILL        NUMBER,
    DAYS        NUMBER,
    CARDIO        NUMBER,
    TIME        DATE
);
ALTER TABLE MEMBER ADD RECENT VARCHAR2(4000);
ALTER TABLE MEM_DATE RENAME COLUMN CAL TO STOPWATCH;

INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'dumbbell', '덤벨', 'ダンベル', 'Dumbbell'
);
INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'pullup', '풀업바', '懸垂バー', 'Pull-Up Bar'
);
INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'band', '밴드', 'バンド', 'Band'
);
INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'cycle', '사이클', 'サイクル', 'Cycle'
);
INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'treadmill', '러닝머신', 'トレッドミル', 'Treadmill'
);
INSERT INTO EQUIPMENT (
    equip_id, name_ko, name_jp, name_en
) VALUES (
    'cali', '맨몸', '素肌', 'Calisthenics'
);

INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'chest', '가슴', '大胸筋', 'Chest'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'back', '등', '背筋', 'Back'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'leg', '하체', '下半身', 'Leg'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'shoulder', '어깨', '肩', 'Shoulder'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'triceps', '삼두', '上腕三頭筋', 'Triceps'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'biceps', '이두', '上腕二頭筋', 'Biceps'
);
INSERT INTO MUSCLE (
    musc_id, name_ko, name_jp, name_en
) VALUES (
    'core', '코어', '腹筋', 'Abs/Core'
);

COMMIT;